# -*- coding: utf-8 -*-
"""Streamlit_ShortStraddle-Log.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nvwItJRRss7UjLu4o1XVB5iXh-XGatOX
"""

import streamlit as st
import time
import os

st.title("Trading Strategy Outcome Dashboard")

st.markdown("""
This dashboard displays live updates of your trading strategy outcomes.
The page auto-refreshes every few seconds.
""")

# Container to display log data
log_container = st.empty()

# Function to read the log file
def read_log():
    log_file = "strategy_log.txt"
    if os.path.exists(log_file):
        with open(log_file, "r") as f:
            return f.read()
    else:
        return "No log data available yet."

# Option to stop auto-refresh
stop_refresh = st.checkbox("Stop Auto-Refresh", value=False)

if not stop_refresh:
    # Auto-refresh the log every 2 seconds
    log_data = read_log()
    log_container.text_area("Strategy Log", log_data, height=400)
    time.sleep(2)
    st.experimental_rerun()
else:
    st.write("Auto-refresh is stopped. Refresh the page manually to see new updates.")